### ISSUE TITLE
Create the simple Yocto project

### ISSUE THREAD

**Issue by bburda** [UmlautSoftwareDevelopmentAccount/AP-OperatingSystemInterface#1]
The Poky should be a good start point for setting up the Operating System according to AUTOSAR RS/SWS documents

**Comment by phongt** [comment]
Outcome discussion:

- Use poky master branch
- Layers: poky, meta-virtualization, Adaptive Autosar Platform layer, Adpative Autosar Application layer
- Create a custom distro configuration
- Base on core-image-minimal,  libstdc++, docker-ce, LTP
- Linux yocto rt
- use git sub module for layers
- Support target: QEMU/RPI
- Init system use default now (sysvinit) can change to [systemd](https://www.yoctoproject.org/docs/3.1.1/dev-manual/dev-manual.html#selecting-an-initialization-manager)

**Comment by slci** [comment]
I think we should start with systemd from the beginning. First thing that comes to my mind is resource limitation (required by AP), systemd can make use of cgroups. Does systemvinit have a mechanism for specifying resource control?

**Comment by phongt** [comment]
>Does systemvinit have a mechanism for specifying resource control?

I think systemvinit is very limited. It may not support that.

Sent PR https://github.com/UmlautSoftwareDevelopmentAccount/AP-OperatingSystemInterface/pull/3

If we go with systemd, the configure for Initialization Manager should be done in meta-aap/conf/distro/alsterwasser.conf

**Comment by bburda** [comment]
This was resolved by #3
